<pre>


</pre>

## Start your mySQL Server from a terminal 
(if it isn't already running)

<code>sudo docker start course-mysql</code>
<pre>

</pre>
**Don't forget that, if you use sqlMagic, you need to execute the connection lines in your Notebook!**

<pre>
%load_ext sql
%config SqlMagic.autocommit=False
%sql mysql+pymysql://root:root@127.0.0.1:3306/mysql
</pre>

## Create a new Python3 Jupyter Notebook in your Exam Answers folder

Commit and push this Notebook to GitHub when you are finished.

You must submit your answers to GitHub by 1800h Sept 14.

In [19]:
%load_ext sql
%config SqlMagic.autocommit=False
%sql mysql+pymysql://root:root@127.0.0.1:3306/mysql

'Connected: root@mysql'



## Data Files
Germplasm.tsv and LocusGene.tsv contain the datasets we need for the exam.

Our objective is to create a database to contain the data in these files, insert the data into the database, then query the database in a variety of ways.


## Problem 1:  Controls

Write a Python script that proves that the lines of data in Germplasm.tsv, and LocusGene are in the same sequence, based on the AGI Locus Code (ATxGxxxxxx).  (hint: This will help you decide how to load the data into the database)

In [2]:
import csv 

germplasmfile = open("Germplasm.tsv", "r")   #loading data
locusgenefile = open("LocusGene.tsv", "r")

germplasmfile.seek(0)  #skip header
locusgenefile.seek(0)

listalocus=[]
i=0

for line1 in germplasmfile.readlines():  #loop1: reads germplasm and finds AGIcode
    listalocus.append(line1.split("\t")[0])

for line2 in locusgenefile.readlines(): #loop2: reads locusgene and finds AGIcode  
    line2 = line2.split("\t")[0]
    if listalocus[i] == line2: #finds if the AGIcode from loop1 is also in loop2
        print("present in both")
    else:
        print("no match")
    
    i=i+1

match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match

## Problem 2:  Design and create the database.  
* It should have two tables - one for each of the two data files.
* The two tables should be linked in a **1:1 relationship**
* you may use either sqlMagic or pymysql to build the database

In [24]:
%load_ext sql
%sql mysql+pymysql://root:root@127.0.0.1:3306/mysql
            
%sql CREATE DATABASE examdatabase;           
%sql use examdatabase;

%sql CREATE TABLE locus_gene(locus VARCHAR(9) PRIMARY KEY NOT NULL, \
                             gene VARCHAR(20) NOT NULL, protein_length INTEGER NOT NULL);  #locus column as the primary key in both tables (this column has unique values in the tables and links both tables): already 1:1 match
%sql CREATE TABLE germplasm(locus VARCHAR(9) PRIMARY KEY NOT NULL, \
                            germplasm VARCHAR(25) NOT NULL, phenotype VARCHAR(500) NOT NULL, pubmed INTEGER NOT NULL);
#%sql DROP TABLE germplasm_table;
#%sql DROP TABLE locus_gene_table;
#%sql show tables
#%sql describe germplasm_table

The sql extension is already loaded. To reload it, use:
  %reload_ext sql
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
(pymysql.err.ProgrammingError) (1007, "Can't create database 'examdatabase'; database exists")
[SQL: CREATE DATABASE examdatabase;]
(Background on this error at: http://sqlalche.me/e/f405)
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
0 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql

InternalError: (pymysql.err.InternalError) (1050, "Table 'locus_gene' already exists")
[SQL: CREATE TABLE locus_gene(locus VARCHAR(9) PRIMARY KEY NOT NULL,                               gene VARCHAR(20) NOT NULL, protein_length INTEGER NOT NULL);]
(Background on this error at: http://sqlalche.me/e/2j85)

In [25]:
%sql describe germplasm
#%sql describe locus_gene

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
4 rows affected.

[('locus', 'varchar(9)', 'NO', 'PRI', None, ''),
 ('germplasm', 'varchar(25)', 'NO', '', None, ''),
 ('phenotype', 'varchar(500)', 'NO', '', None, ''),
 ('pubmed', 'int(11)', 'NO', '', None, '')]

## Problem 3: Fill the database
Using pymysql, create a Python script that reads the data from these files, and **fills the database**.  There are a variety of strategies to accomplish this.  I will give all strategies equal credit - do whichever one you are most confident with.

In [27]:
import pymysql.cursors  #importing
import csv 

germplasmfile = open("Germplasm.tsv", "r")
locusgenefile = open("")



connection = pymysql.connect(host="localhost", #connecting database
                             user="root",
                             password="root",
                             db="examdatabase",
                             charset="utf8mb4", 
                             cursorclass=pymysql.cursors.DictCursor,
                             autocommit = True
    
try:    
    with connection.cursor() as cursor:
        with open ("Germplasm.tsv", newline= "\n") as file: 
            germplasmfile = csv.reader(file, delimiter="\t", quotechar='"')   
            headers= next(germplasmfile) #removing headers so is selected later
            for row in germplasmfile:
                sql = "INSERT INTO germplasmtab(locus, germplasm, phenotype, pubmed) VALUES(%s,%s,%s,%s)" #"%s" is referring to the data in the germplasmfile, one for each column
                cursor.execute(sql, tuple(row)) #selects the data in 'row'
                results = cursor.fetchall() 
                print(results)       
                print("")
        
finally:
connection.close()

SyntaxError: invalid syntax (<ipython-input-27-1775f3b3dec1>, line 16)

In [26]:
%sql SELECT * FROM germplasm; #comprobation of the table

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
32 rows affected.

[('AT1G01040', 'CS3828', 'Increased abundance of miRNA precursors.', 17369351),
 ('AT1G01060', 'lhy-101', 'The mutant plants are hypersensitive to both FRc and Rc light treatments in hypocotyl elongation and exhibits a small reciprocal enlargement in cotyledon area, albeit not statistically significant.', 16891401),
 ('AT1G01140', 'SALK_058629', 'hypersensitive to low potassium media', 17486125),
 ('AT1G01220', 'SALK_012400C', 'fkgp-1 mutants have about 40 times more L-fucose than wild type Arabidopsis plants, but the levels of other monosaccharides do not appear to differ s ... (41 characters truncated) ... henotypic abnormalities were observed in the fkgp-1 mutants, nor were any differences in the sugar composition of cell wall polysaccharides detected.', 18199744),
 ('AT2G03720', 'SALK_042433', 'Multiple straight hairs', 16367956),
 ('AT2G03800', 'gek1-1', 'Ethanol hypersensitivity.', 15215505),
 ('AT2G04240', 'xerico', 'Resistant to exogenous ABA. Seeds contained lower amounts of endogenous ABA than wildtype.', 17933900),
 ('AT2G05210', 'pot1-1', 'No visible phenotype.', 17627276),
 ('AT3G02130', 'rpk2-2', 'The homozygous progeny is indistinguishable from wild-type plants during vegetative growth but showed several morphological alterations after bolting. These plants displayed enhanced inflorescence branching and formed three times as many siliques and flowers as did wild-type plants.', 17419837),
 ('AT3G02140', 'afp4-1', 'Decreased germination on high concentrations of glucose and sorbitol.', 18484180),
 ('AT3G02230', 'rgp1-1', 'rgp1-1 mutants have significantly lower levels of UDP-L-arabinose mutase activity compared to wild-type plants and significantly lower levels of arabinose in their cell walls.', 21478444),
 ('AT3G02260', 'tir3-1 RGLG1:rglg1 rglg2', 'The triple homozygous progeny has low viability, accumulated anthocyanin, and all plants died before shoot emergence.', 17586653),
 ('AT3G02310', 'sep2-1', 'Non-described subtle phenotype.', 10821278),
 ('AT3G02680', 'atnbs1-1', 'Significantly smaller when grown in the presence of methyl methanosulfonate (MMS) with root growth.  Normal growth under standard growth conditions.', 17672843),
 ('AT3G02850', 'CS3816', 'The skor-1 mutant is sensitive to toxic cations in addition to K+ depletion.', 17568770),
 ('AT3G02870', 'vtc4-1', 'ascorbate deficient', 16595667),
 ('AT3G03260', 'hdg8-1', 'No visible phenotype.', 16778018),
 ('AT4G14790', 'pdd17', 'Defective pollen development.', 19237690),
 ('AT4G15210', 'bmy1-2', 'Plants cold-shocked for 6h have an increased starch content compared to wildtype.', 16297066),
 ('AT4G15560', 'cla1-1', 'Mutant seeds grown on medium supplemented with non-phosphorylated synthetic 1-deoxy-D-xylulose (DX) develop green leaves.', 10982425),
 ('AT4G15570', 'maa3', 'Homozygotes are not recovered. Female gametophyte development is delayed and asynchronous. During fertilization, fusion of polar nuclei does not occur. Polar nuclei nucloeli are smaller than WT.', 18772186),
 ('AT4G15802', 'Athspb-2', 'Early flowering, reduced fertility, aborted seeds.', 20388662),
 ('AT4G15880', 'esd4-2', 'Decreased mRNA levels of the floral repressors FLC and MAF4 and increased mRNA levels of the floral activators FT and SOC1.', 17513499),
 ('AT4G16420', 'prz1-1', 'Altered response to auxin and cytokinin', 12747832),
 ('AT4G16480', 'atint4-2', 'No visible phenotype.', 16603666),
 ('AT5G10480', 'pas2-3', 'Segregates 25% embryo lethal.', 18799749),
 ('AT5G10510', 'plt3-1', 'Short roots and shortened root meristem.', 17960244),
 ('AT5G11110', 'kns2', 'Defects are specific to pollen exine structure. Smaller mesh size in the exine structure. Increased number of baculae. Fully fertile.', 18779216),
 ('AT5G11260', 'hy5-101', 'Under FRc conditions, the length mutant hypocotyls is increased compared to that of wild-type plants.  Under Rc conditions, the hypocotyl length is also increased and the cotyledon area is smaller.', 16891401),
 ('AT5G11510', 'myb3r4-1', 'No visible phenotype.', 17287251),
 ('AT5G12200', 'pyd2-2', 'The pyd2-2 mutant has a wild-type appearance under normal growth conditions. Pyrimidine nucleotide and uridine levels are not changed in the mutant, but uracil levels are increased. These mutants cannot grow normally when uracil is provided as a sole nitrogen source.', 19413687),
 ('AT5G13290', 'crn-1', 'Increased meristem size. Vegetative meristems are are 30% larger than wild type. After bolting inflorescence meristems are enlarged and occasionally fasciated. Flowers occasionally produce extra organs in the first 3.', 12345678)]

In [28]:
import pymysql.cursors
import csv


connection = pymysql.connect(host="localhost",
                             user="root",
                             password="root"',
                             db="examdatabase",
                             charset="utf8mb4",  
                             cursorclass=pymysql.cursors.DictCursor)

connection.autocommit(True)
try:    
    with connection.cursor() as cursor:
        with open ("LocusGene.tsv", newline= "\n") as file:
            locusgenefile = csv.reader(file, delimiter="\t", quotechar='"')
            headers = next(locusgenefile) 
            for row in locusgenefile:
                #print(row)
                sql = "INSERT INTO locusgenetab(locus, gene, proteinlengh) VALUES (%s,%s,%s)" 
                cursor.execute(sql, tuple(row)) 
                results = cursor.fetchall()
                print(results)       
                print("")
        
finally:
connection.close()

IndentationError: expected an indented block (<ipython-input-28-618d03913262>, line 27)

In [29]:
%sql SELECT * FROM locus_gene;   #comprobation of the table

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
32 rows affected.

[('AT1G01040', 'DCL1', 332),
 ('AT1G01060', 'LHY', 290),
 ('AT1G01140', 'CIPK9', 223),
 ('AT1G01220', 'FKGP', 190),
 ('AT2G03720', 'MRH6', 189),
 ('AT2G03800', 'GEK1', 196),
 ('AT2G04240', 'XERICO', 256),
 ('AT2G05210', 'POT1A', 221),
 ('AT3G02130', 'RPK2', 284),
 ('AT3G02140', 'TMAC2', 300),
 ('AT3G02230', 'RGP1', 301),
 ('AT3G02260', 'BIG', 279),
 ('AT3G02310', 'SEP2', 175),
 ('AT3G02680', 'NBS1', 190),
 ('AT3G02850', 'SKOR', 234),
 ('AT3G02870', 'VTC4', 311),
 ('AT3G03260', 'HDG8', 194),
 ('AT4G14790', 'SUV3', 312),
 ('AT4G15210', 'BAM5', 313),
 ('AT4G15560', 'DXS', 219),
 ('AT4G15570', 'MAA3', 294),
 ('AT4G15802', 'HSBP', 254),
 ('AT4G15880', 'ESD4', 265),
 ('AT4G16420', 'ADA2B', 279),
 ('AT4G16480', 'INT4', 284),
 ('AT5G10480', 'PAS2', 301),
 ('AT5G10510', 'AIL6', 310),
 ('AT5G11110', 'SPS2', 232),
 ('AT5G11260', 'HY5', 221),
 ('AT5G11510', 'MYB3R-4', 336),
 ('AT5G12200', 'PYD2', 310),
 ('AT5G13290', 'CRN', 189)]

## Problem 4: Create reports, written to a file

1. Create a report that shows the full, joined, **content of the two database tables (including a header line)**

2. Create a joined report that only includes the Genes **SKOR and MAA3**

3. Create a report that counts the number of entries for each Chromosome **(AT1Gxxxxxx to AT5Gxxxxxxx)**

4. Create a report that shows the average protein length for the genes on each Chromosome **(AT1Gxxxxxx to AT5Gxxxxxxx)**

**When creating reports 2 and 3, remember the "Don't Repeat Yourself" rule!** 

All reports should be written to **the same file**.  You may name the file anything you wish.

In [32]:
#4.1 Create a report that shows the full, joined, content of the two database tables (including a header line)

import csv
import io
import pymysql

connection = pymysql.connect(host="localhost",
                             user="root",
                             password="root",
                             db="examdatabase",
                             charset="utf8mb4", 
                             cursorclass=pymysql.cursors.DictCursor,
                             autocommit = True)

try:
    with connection.cursor() as cursor:
        sql = "select * from germplasm, locus_gene where germplasm.locus = locus_gene.locus"
        cursor.execute(sql)  
        results = cursor.fetchall()
except:
    print("Extraction error")

# Write the report
report_file = open("report_EXAM2.tsv", "w")
report_file.write("Exercise 4.1\n")
writer = csv.DictWriter(report_file, delimiter = '\t', quotechar = '"', fieldnames = results[0].keys())
writer.writeheader()
writer.writerows(results)
report_file.close()

In [38]:
#4.2 Create a joined report that only includes the Genes SKOR and MAA3

try:
    with connection.cursor() as cursor:
        sql = '''select * from germplasm, locus_gene where germplasm.locus = locus_gene.locus and (locus_gene.gene = "SKOR" or locus_gene.gene = "MAA3")'''
        cursor.execute(sql)  
        results = cursor.fetchall()
except:
    print("Extraction error")
    
# Write the report
report_file = open("report_EXAM2.tsv", "a")
report_file.write("\nExercise 4.2\n")
writer = csv.DictWriter(report_file, delimiter = "\t", quotechar = '"', fieldnames = results[0].keys())
writer.writeheader()
writer.writerows(results)
report_file.close()

In [39]:
#4.3 Create a report that counts the number of entries for each Chromosome (AT1Gxxxxxx to AT5Gxxxxxxx)
try:
    with connection.cursor() as cursor:
        sql = '''select locus from germplasm'''
        cursor.execute(sql)  
        results = cursor.fetchall()
except:
    print("Extraction error")
    
report_file = open("report_EXAM2.tsv", "a")
report_file.write("\nExercise 4.3\n")
chromo_list = list() #chromosome numebers
for item in results:
    chromo_list.append(int(item["locus"][2])) #third character-> all loci (chromosome number)
for number in range(1, 6):
    report_file.write(f"Chromosome {number}: {chromo_list.count(number)} genes in the database\n")
report_file.close()

In [40]:
#4.4 Create a report that shows the average protein length for the genes on each Chromosome (AT1Gxxxxxx to AT5Gxxxxxxx)
report_file = open("report_EXAM2.tsv", "a")
report_file.write("\nExercise 4.4\n")
try:
    with connection.cursor() as cursor:
        for number in range(1,6):
            sql = f'''select avg(protein_length) from locus_gene where locus regexp '^..{number}' '''
            cursor.execute(sql)  
            results = cursor.fetchall() 
            report_file.write(f"Average protein length in chromosome {number}: {list(results[0].values())[0]}\n")
except:
    print("Extraction error")
    connection.close()
report_file.close()

<pre>

</pre>
## Don't forget to commit and push your answers before you leave!

It was wonderful to have you in my class!  I hope to see you again soon!

Good luck with your careers!!

Mark


**THANK YOU VERY MUCH FOR YOUR CLASSES MARK! See you in the course Challenges in Computer Programming!!**

**Marina**